[target.riscv32imc-unknown-none-elf]
runner = "espflash flash -T partition-table.csv --monitor --chip esp32c3"

[env]
ESP_LOG="info"
WIFI_SSID = "MY_WIFI_SSID"
WIFI_PASS = "MY_WIFI_PASS"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
